baseURL = "https://st0rm.win"
theme = "risotto"
title = "frosty@world"
author = "frosty"

[params.theme]
palette = "gruvbox-dark"

[params.about]
title = "frosty"
description = "Hobbyist developer and Linux enthusiast"

[[params.socialLinks]]
icon = "fa-brands fa-git-alt"
title = "Codeberg"
url = "https://codeberg.org/frosty"

[[params.socialLinks]]
icon = "fa-solid fa-camera"
title = "Flickr"
url = "https://flickr.com/photos/frostyfalls"

[[params.socialLinks]]
icon = "fa-solid fa-comment"
title = "Fediverse"
url = "https://wetdry.world/@broadview"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:passedgoandgot200@gmail.com"

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "machines"
name = "Machines"
url = "/machines/"
weight = 10

[markup.goldmark.renderer]
unsafe = true
